### PR TITLE
Added support for in-repo addons

### PR DESCRIPTION
**Pull request by fushi**
Adds support for in-repo addons/engines, and their 'addon' folder.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@fushi sorry for the long delay in taking a look at this! It seems that the tests are all failing with maximum call stack size exceeded. Any ideas what is going on there or how to fix it?

**Comment by kratiahuja** [comment]
@rwwagner90 / @fushi any update on this PR? Would love to see this land soon.

**Comment by rwwagner90** [comment]
@kratiahuja no updates really. I spoke to @rwjblue about releasing his spike https://github.com/kategengler/ember-cli-code-coverage/pull/141 and I think we are in agreement that we should go ahead and get a basic version of it in, and then add back features as we go. I'll likely merge that and work on it some this weekend, but no guarantees it'll fix this issue. Might be awhile before we can bolt everything back on.

**Comment by kratiahuja** [comment]
@rwwagner90 any update on getting code coverage working for in-repo addons?

**Comment by rwwagner90** [comment]
@kratiahuja still no updates. There are two spikes that we need to get in, and @rwjblue has another idea now too as well, so waiting on a decision before pushing forward.

**Comment by rwwagner90** [comment]
in-repo addons should be supported as of 1.0.0-beta.2. Please try it out and let us know if you experience any issues!

**Pull request closed without merging**
