### PR TITLE
Fixes the hanging issue of #88

### PR DESCRIPTION
**Pull request by ming-codes**
Fixes the hanging issue of #88

Also changed `onload` to `onreadystatechange`.

`onload` doesn't trigger on chromium.

### CODE REVIEW

**Comment by ming-codes** [comment]
A side note, why aren't we using jQuery for this?

**Comment by rwjblue** [comment]
Because apps can run without jQuery and I wanted to test coverage of them.

**Comment by ming-codes** [comment]
Ember still depends on jQuery though. This is an Ember add on. The tests are likely won't run if jQuery is not present.

**Comment by rwwagner90** [comment]
@ming-codes this PR fixes the `Cannot find module 'rsvp'` issue?

**Comment by ming-codes** [comment]
@rwwagner90 No it does not. The PR mainly addresses my own issues with 0.3.10 release.

**Comment by samtsai** [comment]
FYI @rwwagner90 https://github.com/kategengler/ember-cli-code-coverage/pull/90#issuecomment-271859054 has been resolved with: https://github.com/kategengler/ember-cli-code-coverage/pull/94

This has been merged and `0.3.11` has been released with a few other fixes.

**Comment by ultimatemonty** [comment]
are other folks running into this problem? I see it consistently on 0.3.11 and ember-cli 2.8.0

**Comment by kellyselden** [comment]
@ultimatemonty I have no more issues with the current release of this and ember-cli.

**Comment by ming-codes** [comment]
@ultimatemonty Can you checkout the PR and see if it fixes your issue?

**Comment by ultimatemonty** [comment]
@ming-codes can confirm this branch fixes the issue. I updated ember-cli to 2.10.1 and still failing on the 0.3.11 release. I'm unable to update to ember-cli 2.11.1 due to ember 2.11 breaking part of our app (😠 at not testing on beta branches)

**Comment by gabz75** [comment]
@ming-codes - your branch fixes the issue for me too, thanks!
```
ember-cli: 2.11.0
node: 6.0.0
os: darwin x6```

**Comment by ming-codes** [comment]
Pinging @rwjblue @kategengler!

Anything else I need to do to get this merged?

**Comment by ultimatemonty** [comment]
ping @rwjblue @kategengler - is there a chance this will get merged? I'm affected by the issue and ended up forking this repo and applying this fix so I could stay up-to-date and functional.

cc @ming-codes

**Comment by ming-codes** [comment]
Just rebased on top of master. Let me know if there's anything else I need to do.

**Comment by ming-codes** [comment]
@kellyselden I'm still having the hanging issue with `0.4.0`. This is against PhantomJS `2.1.1`. This patch fixes the issue.

**Comment by kellyselden** [comment]
Released in v0.4.1.

**Comment by ultimatemonty** [comment]
thanks @kellyselden !

**Pull request merged**
