### PR TITLE
ember-cli-typescript v2 fix

### PR DESCRIPTION
**Pull request by lifeart**
image

### CODE REVIEW

**Comment by scottkidder** [comment]
Can we get this merged and a beta release?

**Comment by gmurphey** [comment]
We have a project that we've just started to convert to TS. 1.0.0-beta.8 produces coverage reports for our JS, but not TS. This patch doesn't produce reporting for any file types.

I've followed the instructions here: https://github.com/kategengler/ember-cli-code-coverage#typescript-integration

Is there any other config changes needed to get this patch working?

**Comment by lifeart** [comment]
@gmurphey this patch for `ember-cli-typescript@2.x.x`. (integrated with babel)

Before `ember-cli-typescript@2.x.x` we use `1.0.0-beta.8` with described in documentation `TS` section configuration and it's works fine.

**Comment by lifeart** [comment]
But, looks like 
```js
const hasEmberCliTypescript = this.project.findAddonByName('ember-cli-typescript');
```
may not work perfectly, for `e-c-ts@2+` try this change 
```js
const hasEmberCliTypescript = true
```

**Comment by gmurphey** [comment]
Sorry, should've mentioned that we are using `ember-cli-typescript@2.0.0`. Was working fine beforehand.

Changing the `hasEmberCliTypescript` flag to `true` in `index.js` still has the same effect for me. No coverage is reported for any filetypes.

image

I'll keep digging and I'll work on producing a smaller, shareable reproduction.

**Comment by gmurphey** [comment]
Also worth mentioning that we get coverage reported for `.js` files after downgrading to `ember-cli-code-coverage@1.0.0-beta.8` (still using `ember-cli-typescript@2.0.0`)

image

**Comment by lifeart** [comment]
@gmurphey did you change `package.json`?

```
 "ember-addon": {
    "configPath": "tests/dummy/config"	    "configPath": "tests/dummy/config",
    "before": "ember-cli-typescript"
  },	  },
```
^ to this lines

**Comment by gmurphey** [comment]
@lifeart I have the following in our project's `package.json`:

```
"ember-cli-code-coverage": "github:lifeart/ember-cli-code-coverage#patch-2"
```

It seems to have all the changes from this PR included, including the changes to the addon's `package.json`.

**Comment by gmurphey** [comment]
Finally had a chance to recreate a reproduction. https://github.com/gmurphey/typescript-coverage-repro 

Running `COVERAGE=true ember test` results in no coverage for any files.

**Comment by rwwagner90** [comment]
@gmurphey @lifeart where are we on this? If I am understanding correctly, some of you think this works and others see no coverage?

**Comment by makepanic** [comment]
We're also seeing no coverage when trying `github:lifeart/ember-cli-code-coverage#patch-2` in an app which uses TS + JS with `ember-cli-typescript@^2`

**Comment by luketheobscure** [comment]
We're also seeing no coverage with this patch and `ember-cli-typescript@^2`. I made sure we got the commit with `"before": "ember-cli-typescript"`.  Manually changing the line to `const hasEmberCliTypescript = true` doesn't change anything. The line `this.project.findAddonByName('ember-cli-typescript')` does appear to be detecting the typescript addon correctly.

Also, with version 1.0.0-beta.8 we would get coverage on the one or two stray JavaScript files we had (just no coverage for TS files). With this patch we don't get any coverage.

**Comment by luketheobscure** [comment]
I may have spoken too soon. I'll update when I have something more definitive.

**Comment by lifeart** [comment]
Hm, so strange, we have correct `.ts` + `.js` coverege using this modification, lemme create reproduction app

**Comment by luketheobscure** [comment]
I can confirm now that it's not working for us. I tried in an addon and inside an app, with TS and JS files. This is all on the Ember 3.11 family of projects, on fairly new repos.

**Comment by NullVoxPopuli** [comment]
This doesn't work for me either, I get a bunch of these errors:
image

**Comment by NullVoxPopuli** [comment]
it doesn't seem like it can find any of my modules. :-\
```
imported from `(require)`
            Error: Could not find module `pods/components/pod/chat/chat-history/message/embedded-resource/metadata-preview/component` imported from `(require)`
                at missingModule (http://0.0.0.0:7357/assets/vendor.js:252:11)
                at findModule (http://0.0.0.0:7357/assets/vendor.js:263:7)
                at requireModule (http://0.0.0.0:7357/assets/vendor.js:29:15)
                at http://0.0.0.0:7357/438686106336545/tests/index.html?hidepassed&seed=1q6new8nlo7:135:9
                at Array.forEach (<anonymous>)
                at sendCoverage (http://0.0.0.0:7357/438686106336545/tests/index.html?hidepassed&seed=1q6new8nlo7:133:5494)
                at Object.<anonymous> (http://0.0.0.0:7357/438686106336545/tests/index.html?hidepassed&seed=1q6new8nlo7:166:7)
```

**Comment by rwwagner90** [comment]
@NullVoxPopuli is `pods/components/pod/chat/chat-history/message/embedded-resource/metadata-preview/component` the correct path? Seems off. Could be worth trying without using a `podModulePrefix`.

**Comment by NullVoxPopuli** [comment]
@rwwagner90 my app and tests work, and I just manually verified that the component for that path is rendered. so the path is correct.

I'm using component-co-location with pods, so maybe that's why the path looks weird.

**Comment by NullVoxPopuli** [comment]
After upgrading to the latest ember canary + glimmer alpha.13, I got this: 
image
Which... it is progress -- my tests ran, but just no coverage was tracked

**Comment by rwwagner90** [comment]
@NullVoxPopuli it's definitely likely new stuff like co-location will cause issues. As things change in Ember, this probably will need lots of work. I don't have the time to look into it myself, but would love some help getting things working here again 😃

**Comment by NullVoxPopuli** [comment]
should there be a way for e-c-code-coverage to crawl all files known to ember? seems weird to have to change a bunch of stuff everytime project layout changes.

**Comment by rwwagner90** [comment]
I really don't know. I've never had a firm grasp on this stuff.

**Comment by luketheobscure** [comment]
I can confirm that this is still broken with ember-cli-typescript v3.0. Tried with latest release, and with this branch from lifeart, with and without the `ember-addon: { before: ... }` stuff. This branch makes the TS files show up, but it doesn't actually get any coverage (everything is at 0%).

**Comment by rwwagner90** [comment]
If anyone would like to try to add TS support, we would appreciate the help!

**Comment by mdeanjones** [comment]
Adding to the solution by @lifeart - https://github.com/nsf-open/ember-cli-code-coverage/commit/fe27b61f754b575f1cd15691b747c66b43dae964

Result is `foo-project/addon/services/bar-service` instead of `services/bar-service`. Worked for us anyway. Always the little things.

**Comment by rwwagner90** [comment]
Would love to have someone help with a definitive solution here. I do not know much about TypeScript. @kategengler should we work towards supporting this? Is this addon still going to work with Octane the same as before?

**Comment by luketheobscure** [comment]
Just tried out the commit at https://github.com/nsf-open/ember-cli-code-coverage/commit/fe27b61f754b575f1cd15691b747c66b43dae964 and it appears to work! We still needed the `"before": "ember-cli-typescript"` though. 

This is in a project that checks the boxes on almost all the corner cases... It's an engine, using pods layout, without a pod module prefix, in a workspace.

**Comment by rwwagner90** [comment]
@lifeart @NullVoxPopuli can you guys try out the change by @mdeanjones and see if it works for you? If it does, we should try to get it merged in.

**Comment by NullVoxPopuli** [comment]
@rwwagner90 confirmed fix on emberclear!

**Comment by makepanic** [comment]
Can confirm that https://github.com/nsf-open/ember-cli-code-coverage/commit/fe27b61f754b575f1cd15691b747c66b43dae964 fixes the coverage generation for us (addon + app in monorepo). :+1:

**Comment by lifeart** [comment]
PR updated!

**Comment by rwwagner90** [comment]
@lifeart thanks! Did you confirm the changes work for you as well?

**Comment by rwwagner90** [comment]
If we can get the tests passing, I'm in favor of merging 👍

**Comment by gmurphey** [comment]
> Finally had a chance to create a reproduction. https://github.com/gmurphey/typescript-coverage-repro
> 
> Running `COVERAGE=true ember test` results in no coverage for any files.

Updated the original reproduction and confirmed that coverage is being generated there as well!

**Comment by NullVoxPopuli** [comment]
I also confirm that this branch / PR fixes the _html_ coverage report.

I'm currently having issues with the lcov report / codeclimate -- not sure where the issue is yet

**Comment by lifeart** [comment]
@rwwagner90 yes, it's working.
Regarding CI, I see list of outdated deps issues, it may be an different PR to upstream whole ember-cli-code-coverage project, including it's tests.

**Comment by lifeart** [comment]
Pushed my attempts to upstream addon, If somebody has capacity to check it or fix CI issues - ping me, I will add you as maintainer for such branch.
https://github.com/kategengler/ember-cli-code-coverage/pull/223

**Pull request closed without merging**
