### PR TITLE
Move ember-cli-babel to dependencies

### PR DESCRIPTION
**Pull request by rmachielse**
DEPRECATION: Addon test support files were detected in `ember-cli-code-coverage/addon-test-support`, but no JavaScript preprocessors were found for `ember-cli-code-coverage`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to `dependencies` (NOT `devDependencies`) in `ember-cli-code-coverage`'s `package.json`.

### CODE REVIEW

**Comment by rmachielse** [comment]
@kategengler @rwjblue anyone able to give this approval so we can see if the tests work? This should be a trivial change.

**Comment by rmachielse** [comment]
@kategengler looks like the tests are failing for the same reason they are failing on master, but not exactly sure what that is

**Comment by rmachielse** [comment]
@kategengler rebased on master!

**Comment by rwjblue** [comment]
Thanks @rmachielse!

**Comment by rwjblue** [comment]
Thanks @rmachielse!

**Pull request merged**
