### PR TITLE
adds coverage support for transpiled javascript source

### LINKED ISSUE #55: Does not work with CoffeeScript
It looks like files compiled from CoffeeScript (using ember-cli-coffeescript) are not included when calculating code coverage. They don't show up on any of the reports.

### PR DESCRIPTION
**Pull request by theseyi**
- this should resolve #55 
- coverage is instrumented for transpiled sources

### CODE REVIEW

**Comment by championswimmer** [comment]
what's the status of this ? 

this allows coverage on .ts files, that was not possible earlier. 

would love to see this merged

**Comment by rwwagner90** [comment]
@adamjmcgrath do the new betas support transpiled sources? Typescript, Coffeescript, etc? If not, what would it take to land some of the tweaks from this PR?

**Comment by adamjmcgrath** [comment]
>  do the new betas support transpiled sources?

I just tested this on [https://github.com/dfreeman/why-yes-i-do-have-types](dfreeman/why-yes-i-do-have-types)

I had to add `ts` to the list of extensions here: https://github.com/kategengler/ember-cli-code-coverage/blob/master/index.js#L204

But after that it seemed to work ok (not sure why `branch` coverage is 1/1 - possibly something to do with how it's transpiled?)

screen shot 2018-02-21 at 08 09 24

I would have thought, that for an `ember-cli-typescript` project, that `extensionsForType('js')` would return `ts` as well as `js`? If that were the case this would work without any additional effort.

**Comment by rwwagner90** [comment]
@adamjmcgrath could we expose a config option to pass the extensions to report coverage for, like this PR did?

**Comment by dfreeman** [comment]
> I just tested this on https://github.com/dfreeman/why-yes-i-do-have-types

😆 glad that's getting some use

> I would have thought, that for an ember-cli-typescript project, that extensionsForType('js') would return ts as well as js?

We're doing some kind of odd things in ember-cli-typescript, but I think if we associate the `ts` extension to our _ahem_ fake preprocessor it should fix `extensionsForType()`.

**Comment by rwwagner90** [comment]
@dfreeman so this all works with typescript now, right? Can we close this?

**Comment by dfreeman** [comment]
@rwwagner90 with `master` of ember-cli-code-coverage and source maps turned on, everything seems to work _mostly_ correctly. Files seem to show up, and the coverage numbers appear to be right. The one odd thing is that the hit rates in the left gutter seem to be off by one line, and I'm not sure what's causing that.

**Comment by rwwagner90** [comment]
@dfreeman I would consider that another bug. Do you mind opening an issue with the details and a screenshot of what you observed please? I am closing this issue for now.

**Pull request closed without merging**
