### PR TITLE
Module unification support

### PR DESCRIPTION
**Pull request by abhilashlr**
What this PR does?
Fix for #197

- [x] Partial support for module unification based folder structure.
- [x] Coverage takes -test.js files that are part of the individual folders. (Needs help)
- [x] Add readme

### CODE REVIEW

**Comment by rwwagner90** [comment]
@kategengler do you have any insights on the items marked as `needs help` for this PR? I haven't tried using MU myself, and wanted to get your input, since you are likely more familiar with all the changes that would be necessary here and the inner workings on MU apps.

**Comment by kategengler** [comment]
I'm not sure. I'll investigate.

**Comment by NullVoxPopuli** [comment]
I'm not sure if I've configured something wrong with sourcemaps, but my line annotations are way off
image

**Comment by abhilashlr** [comment]
@NullVoxPopuli are tests running twice for you as well?

**Comment by NullVoxPopuli** [comment]
I think things are only running once for me

**Comment by NullVoxPopuli** [comment]
proof: https://gitlab.com/NullVoxPopuli/emberclear/-/jobs/105285122

**Comment by abhilashlr** [comment]
@rwwagner90 @kategengler Looks like all the points are addressed now. Travis seems to fail and should be fixed by #202

**Comment by abhilashlr** [comment]
@rwwagner90 there is no change in this PR with respect to ember-cli-babel. Can you please help me in resolving that issue if so?

**Comment by abhilashlr** [comment]
@rwwagner90 yes it does report them correctly.

**Comment by NullVoxPopuli** [comment]
@abhilashlr, you don't have issues with highlighting accuracy? Maybe I configured typescript wrong. Hmm

**Comment by abhilashlr** [comment]
Nope @NullVoxPopuli, In my sample app that has MU without typescript, highlight seems fine.

**Comment by NullVoxPopuli** [comment]
if someone could review the configuration of my typescript setup, that'd be great... cause something is off.

tsconfig:
```
{
  "compilerOptions": {
    "target": "ES2017",
    "allowJs": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "noEmitOnError": false,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": false,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "baseUrl": ".",
    "module": "es6",
    "paths": {
      "emberclear/config/*": [
        "config/*"
      ],
      "emberclear/tests/*": [
        "tests/*"
      ],
      "emberclear/*": [
        "src/*"
      ],
      "emberclear/src/*": [
        "src/*"
      ],
      "*": [
        "types/*"
      ],
      "@ember": [
        "node_modules/@types/ember/index.d.ts"
      ],
      "fetch": [
        "node_modules/ember-fetch/index.d.ts"
      ],
      "tweetnacl": [
        "node_modules/tweetnacl/nacl.d.ts"
      ]
    }
  },
  "include": [
    "src",
    "tests",
    "types"
  ]
}
``` 

ember-cli-babel.js

```js
  let app = new EmberApp(defaults, {
    hinting: false,
    minifyJS: { enabled: false },
    minifyCSS: { enabled: isProduction },


    babel: {
      sourceMaps: 'inline'
    //   plugins: [
    //     ['@babel/plugin-syntax-decorators', { legacy: true }]
    //   ]
    },

    sourcemaps: {
      enabled: !isProduction,
      extensions: 'js'
    },

    'ember-cli-babel': {
      includePolyfill: false,
      disablePresetEnv: true,
      disableDebugTooling: isProduction,
      // Will not build if uncommented:
      // disableEmberModulesAPIPolyfill: true
      // compileModules: false,
    },
// ...
```

and I'm running coverage with: 

```
COVERAGE=true yarn test
```
where test is defined as:
```
    "test": "yarn ember exam --random",
```

and my coverage report looks like this:
image


the highlighting is super weird -- partial word highlighting and such.. 
it looks like the line-hit counts are correct, or at least align with things that make sense.

So, what have I missed it configuration? or is something wrong?

**Comment by rwwagner90** [comment]
@NullVoxPopuli I resolved the conflict, but not sure if that also will update the other things.

**Comment by NullVoxPopuli** [comment]
hmm, something is still wrong. I'm still getting failures with coverage enabled. :-\

**Comment by rwwagner90** [comment]
@NullVoxPopuli I am not sure how to rebase this, since it is from @abhilashlr's fork.

**Comment by HodofHod** [comment]
@NullVoxPopuli Perhaps try [my fork](https://github.com/HodofHod/ember-cli-code-coverage/tree/Module_Unification_Babel7)? It won't rebase this PR, but it'll tell you if rebasing makes it work for you.

**Comment by NullVoxPopuli** [comment]
@HodofHod almost: https://gitlab.com/NullVoxPopuli/emberclear/-/jobs/142813613

now it looks like coverage-merge doesn't seem to work :(

**Comment by abhilashlr** [comment]
Is there something that needs to be worked on this further? Please let me know

**Comment by NullVoxPopuli** [comment]
I guess, it just needs to work against this: https://github.com/ember-cli/ember-octane-blueprint/

my emberclear code may have something else going on, with typescript being involved and everything.

Just need two smoke tests, I guess: Octane: js + ts (e-c-ts@2)

**Comment by NullVoxPopuli** [comment]
MU, as we know it, has been descoped. This should probs be closed

**Comment by rwwagner90** [comment]
@NullVoxPopuli it will still eventually happen, supposedly, so couldn't hurt to keep this around for a bit.

**Comment by lstrzebinczyk** [comment]
Module unification is now dead, isn't it?

**Comment by NullVoxPopuli** [comment]
yup.

**Comment by rwwagner90** [comment]
Closing since MU is dead

**Pull request closed without merging**
